title = "CNO2d model"

[config]
model_type="CNO2d"

# Model characteristics
n_layers = 4
in_size = 128
in_channels = 1
out_channels = 1

# Overall data properties
alpha = 1.0

learning_rate = 0.001
step_size = 100
gamma = 0.5
weight_decay = 1e-6
physics_importance = 1e-5
boundary_condition_weight = 1e-5
pde_normalizer = 500

batch_size = 64
epochs = 1000



