title = "FNO2d model"

[config]
model_type="FNO2d"

# Model characteristics
n_layers = 4
modes = 32
width = 64
retrain = 42 # seed
in_channels = 1
out_channels = 1
padding = 0
include_grid = 1

# Overall data properties
alpha = 1.0

learning_rate = 0.001
step_size = 100
gamma = 0.1
weight_decay = 1e-6
physics_importance = 1e-4
boundary_condition_weight = 1e-4

batch_size = 64
epochs = 500



