title = "FNO1d model"

[config]
model_type="FNO1d"

# Model characteristics
n_layers = 4
modes = 32
width = 64
retrain = 42 # seed
in_channels = 1
out_channels = 1

# Overall data properties
nu = 0.01
nu_divide_by_pi = true

learning_rate = 0.001
step_size = 20
gamma = 0.5
weight_decay = 1e-6
physics_importance = 0
boundary_condition_weight = 0
pde_normalizer = 500

batch_size = 32
epochs = 20



