[config]
data_path = "temporal/ns_2d/data/data_100_50steps/ns_data_64.h5"
low_res_data_path = "temporal/ns_2d/data/data_100_50steps/ns_data_32.h5"
high_res_data_path = "temporal/ns_2d/data/data_100_50steps/ns_data_128.h5"
n_samples = 100

# --- PHYSICS PARAMETERS ---
# dt = Total Duration / Recorded Steps
# dt = 10.0 / 50 = 0.2
dt = 0.2

# Must match 'visc' in generation script
viscosity = 1e-3