title = "FFNO2d model"

[config]
model_type = "FFNO2d"

# --- ARCHITECTURE ---
in_channels = 1   
out_channels = 1   

# Modes: controls the "resolution" of the operator.
# For 64x64 grid, max is 32. 
# We use 16 to capture physics while filtering high-freq noise.
modes = 16         
width = 64         
n_layers = 4

# Grid: Essential for your sin(x+y) forcing
include_grid = 1   
padding = 0        # Periodic boundaries require 0 padding

# --- TRAINING ---
batch_size = 64

# INCREASED: Randomized sampling makes epochs very fast. 
# You need more epochs to reach convergence.
epochs = 500       

learning_rate = 0.001
step_size = 100     # Decay LR every 50 epochs
gamma = 0.5
retrain = 42 # seed

weight_decay = 1e-5
physics_importance = 0.1 # Optional: Enable if you want PINN loss