[config]
model_type="FNO2d"

# --- Autoregressive Settings ---
in_channels = 1   # 1 history steps
out_channels = 1   # Predicting the next step

# Model characteristics
modes = 12
width = 20
n_layers = 4
padding = 0       # Often needed for non-periodic boundaries
include_grid = 1  # Important: appends x,y coordinates
retrain = 42
physics_importance = 0.1

# Training
batch_size = 64
epochs = 500
learning_rate = 0.001
weight_decay = 1e-6
step_size = 100
gamma = 0.5